server:
  id: 1
  tcp:
    port: 9090
  websocket:
    port: 8090


db:
  driver: com.mysql.jdbc.Driver 
  dialect: org.hibernate.dialect.MySQLDialect
  url: jdbc:mysql://localhost:3306/WISE?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
  user: root
  pswd: wisesoul


logging:
  level:
    com.wise: DEBUG
    org.hibernate: DEBUG